### ISSUE TITLE
File name with dot like pdr.update can't coplete action

### ISSUE THREAD

**Issue by kivannc** [s0/git-publish-subdir-action#73]
I have two repo first one named pdr and second one named pdr.update.
First one can complte action with no problem but pdr.update fails on publish-subdir-action

   - name : Publish Libux-Arm  
      run: dotnet publish -r linux-arm -o raspberrypi
   - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: raspberrypi # The branch name where you want to push the assets
        FOLDER: raspberrypi # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message
        
        
Error log is below for repo named pdr.update

Run s0/git-publish-subdir-action@develop
Cloning into '/tmp/git-publish-subdir-action-33X3B5/repo'...

From https://github.com/3EIndustrialEngineering/pdr.update
 * [new branch]      raspberrypi -> raspberrypi

##[info] Checking if branch raspberrypi exists already
data   raspberrypi

Switched to branch 'raspberrypi'

##[info] Updating branch raspberrypi
##[info] Removing all files from target branch
##[info] Copying all files from /home/runner/work/pdr.update/pdr.update/raspberrypi
cp: cannot overwrite directory './pdr.update' with non-directory

Error: Process exited with code: 1:
cp: cannot overwrite directory './pdr.update' with non-directory

    at ChildProcess.<anonymous> (/home/runner/work/_actions/s0/git-publish-subdir-action/develop/action/dist/index.js:1263[9](https://github.com/3EIndustrialEngineering/pdr.update/runs/6003528746?check_suite_focus=true#step:7:9):20)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:[10](https://github.com/3EIndustrialEngineering/pdr.update/runs/6003528746?check_suite_focus=true#step:7:10)22:16)
    at Socket.<anonymous> (internal/child_process.js:444:[11](https://github.com/3EIndustrialEngineering/pdr.update/runs/6003528746?check_suite_focus=true#step:7:11))
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:[12](https://github.com/3EIndustrialEngineering/pdr.update/runs/6003528746?check_suite_focus=true#step:7:12))

Successfully completed action repo named pdr

Run s0/git-publish-subdir-action@develop
Cloning into '/tmp/git-publish-subdir-action-Y5M0xn/repo'...

From https://github.com/3EIndustrialEngineering/pdr
 * [new branch]      raspberrypi -> raspberrypi

##[info] Checking if branch raspberrypi exists already
data   raspberrypi

Switched to branch 'raspberrypi'

##[info] Updating branch raspberrypi
##[info] Removing all files from target branch
##[info] Copying all files from /home/runner/work/pdr/pdr/raspberrypi
##[info] Pushing
To https://github.com/3EIndustrialEngineering/pdr.git
   f6fb1a6..e70e0[9](https://github.com/3EIndustrialEngineering/pdr/runs/6003463109?check_suite_focus=true#step:7:9)d  raspberrypi -> raspberrypi

**Comment by kivannc** [comment]
I've cleared all folders in raspberrypi branch and then it worked.
